### ISSUE TITLE
Build errors with LVGL v8.3.9

### ISSUE THREAD

**Issue by zjanosy** [lvgl/lv_port_pc_visual_studio#56]
I have checked out the release/v8.3 branch, and I have updated the lvgl submodule to the latest v8.3.9 version. The project worked with the original v8.3.5 version. Now the Visual Studio project does not compile with the errors:
```
1>c1 : fatal  error C1083: Cannot open source file: 'lvgl\src\draw\nxp\vglite\lv_gpu_nxp_vglite.c': No such file or directory
1>c1 : fatal  error C1083: Cannot open source file: 'lvgl\src\draw\nxp\lv_gpu_nxp.c': No such file or directory
```
Apparently these files have been removed from the repo, but they are in the VS project. I tried removing the complete nxp folder manually from the project, but got an error message:
```
Cannot modify an evaluated object originating in an imported file "D:\lvgl\test\lv_port_pc_visual_studio_v8\LVGL.Simulator\LVGL.Portable.vcxitems".
```
I use Visual Studio 2022 Community Edition.

**Comment by MouriNaruto** [comment]
I will update it for fixing the issue.

Kenji Mouri

**Comment by MouriNaruto** [comment]
The issue in release/v8.3 branch should be fixed.

Kenji Mouri

**Comment by zjanosy** [comment]
Thank you! It is working now.

**Comment by kisvegabor** [comment]
Thank you for the prompt update, Kenji!
